

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.util.Calendar;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Leaveentry.java
 *
 * Created on Aug 27, 2014, 10:05:43 PM
 */

/**
 *
 * @author 2
 */
public class Leaveentry extends javax.swing.JFrame {

    /** Creates new form Leaveentry */
    public Leaveentry() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        c1 = new datechooser.beans.DateChooserCombo();
        c2 = new datechooser.beans.DateChooserCombo();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LEAVE ENTRY FORM");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("From");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Employee id");
        jLabel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, 30));

        jLabel5.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("To");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 30, 20));
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, 20));

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 160, -1));

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 160, -1));

        b3.setFont(new java.awt.Font("Arial Black", 3, 11)); // NOI18N
        b3.setForeground(new java.awt.Color(255, 0, 0));
        b3.setText("ADD");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        b4.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        b4.setForeground(new java.awt.Color(255, 0, 0));
        b4.setText("NEW");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, -1, -1));

        b1.setFont(new java.awt.Font("Arial Black", 3, 11)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 0, 0));
        b1.setText("BACK TO ADMINISTRATION");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Employee name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, 20));

        b2.setFont(new java.awt.Font("Arial Black", 3, 11)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 0, 0));
        b2.setText("DELETE");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("LEAVE ENTRY FORM......");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\images\\10-Industrial-Bedrooms-Interior-Design.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
  t1.setText("");
  t2.setText("");
    }//GEN-LAST:event_b4ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
         String eid,ename;
        int y,m,d;
        eid=t1.getText();
        ename=t2.getText();
        Calendar C=c1.getSelectedDate();
        d=C.get(C.DAY_OF_MONTH);
        m=C.get(C.MONTH)+1;
        y=C.get(C.YEAR);
        String frm=(y+"-"+m+"-"+d);

        Calendar C1=c2.getSelectedDate();
        int d1=C1.get(C1.DAY_OF_MONTH);
        int m1=C1.get(C1.MONTH)+1;
        int y1=C1.get(C1.YEAR);
        String till=(y1+"-"+m1+"-"+d1);

        try {
             //code for connectivity
             Class.forName("java.sql.DriverManager");
             Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/factory","root","qwerty");
             Statement s=(Statement)c.createStatement();
             String A="Insert into leaventry values('"+eid+"','"+ename+"','"+frm+"','"+till+"');";
             JOptionPane.showMessageDialog(null,"entry added");
             s.executeUpdate(A);
         } 
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(this,e);
         }
  




    }//GEN-LAST:event_b3ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
       new adminblock() .setVisible(true);
       this.dispose();

    }//GEN-LAST:event_b1ActionPerformed

    private void jLabel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2AncestorAdded

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed

        String A;
        String n=t1.getText();
         String b=t2.getText().toLowerCase();
        try {
             //code for connectivity
             Class.forName("java.sql.DriverManager");
             Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/factory","root","qwerty");
             Statement s=(Statement)c.createStatement();
if (n.equals(""))
    {
     A=" Delete from leaventry where ename like'%"+b+"%';";
    }
    else
     A="delete from  leaventry where eid="+t1.getText()+";";
        JOptionPane.showMessageDialog(null,"entry deleted");
             s.executeUpdate(A);
    } 
        catch(Exception e) 
        {
             JOptionPane.showMessageDialog(this,e);
         }
      
    }//GEN-LAST:event_b2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Leaveentry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private datechooser.beans.DateChooserCombo c1;
    private datechooser.beans.DateChooserCombo c2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables

}
